/*
 * Copyright (C) 2010 Tolven Inc

 * This library is free software; you can redistribute it and/or modify it under the terms of 
 * the GNU Lesser General Public License as published by the Free Software Foundation; either 
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU Lesser General Public License for more details.
 *
 * Contact: info@tolvenhealth.com 
 *
 * @author <your name>
 * @version $Id: TrimResources.java 8704 2014-02-19 09:56:43Z srini.kandula@tolvenhealth.com $
 */

package org.tolven.api.rs.resource;

import java.io.ByteArrayOutputStream;
import java.net.URI;
import java.net.URLEncoder;
import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.naming.InitialContext;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.xml.bind.JAXBException;

import org.apache.log4j.Logger;
import org.tolven.app.TrimLocal;
import org.tolven.app.entity.TrimHeader;
import org.tolven.core.TolvenRequest;
import org.tolven.trim.CE;
import org.tolven.trim.TrimMarshaller;
import org.tolven.trim.ValueSet;
import org.tolven.trim.ex.TrimEx;
import org.tolven.util.ExceptionFormatter;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

@Path("trim")
public class TrimResources extends TolvenResources{
    private static Logger logger = Logger.getLogger(TrimResources.class);

    @EJB
    private TrimLocal trimBean;

    @Context
    private HttpServletRequest request;

    /**
     * Upload a trim header
     * Requires user to have tolvenAdmin permission
     * @return id of created trim
     */
    @Path("upload")
    @POST
    @Consumes(MediaType.APPLICATION_XML)
    public Response uploadTrim(String content) {
        String comment = "";
        boolean autogenerated = false;
        String trimId = getTrimBean().createTrimHeader(content, request.getUserPrincipal().getName(), comment, autogenerated);
        URI createdUri = null;
        try {
            createdUri = new URI(URLEncoder.encode(trimId, "UTF-8"));
        } catch (Exception ex) {
            return Response.status(Status.INTERNAL_SERVER_ERROR).type(MediaType.TEXT_PLAIN).entity(ExceptionFormatter.toSimpleString(ex, "\\n")).build();
        }
        return Response.created(createdUri).build();
    }

    /**
     * Activate uploaded trim headers. the caller should be prepared to call this
     * API in a loop for each time it returns with a status of continued.
     * A return of OK means that there are no more Trims left to activate.
     * Requires user to have tolvenAdmin permission
     */
    @Path("activate")
    @POST
    public Response activateTrims() {
        boolean more = getTrimBean().activateNewTrimHeaders();
        return Response.ok().entity(more).build();
    }

    /**
     * Queue activation of uploaded trim headers
     * Executes asynchronously
     * Requires user to have tolvenAdmin permission
     */
    @Path("queueActivate")
    @POST
    public Response queueActivateTrim() throws Exception {
        getTrimBean().queueActivateNewTrimHeaders();
        return Response.ok().build();
    }

    /**
     * Get a trim by name
     * @param name
     * @return
     */
    @Path("get")
    @GET
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_XML)
    public Response getTrim(@QueryParam("name") String name) {
        TrimHeader trimHeader = getTrimBean().findOptionalTrimHeader(name);
        
        if (trimHeader == null) {
            return Response.status(Status.NOT_FOUND).type(MediaType.TEXT_PLAIN).entity("TrimHeader not found").build();
        }
        return Response.ok().type(MediaType.APPLICATION_XML_TYPE).entity(trimHeader.getTrim()).build();
    }
    
    /**
     * Get a trim by name
     * @param name
     * @return
     */
    @Path("getComputed")
    @GET
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_XML)
    public Response getComputedTrim(@QueryParam("name") String name) {
    	TrimHeader trimHeader = getTrimBean().findOptionalTrimHeader(name);
    	ByteArrayOutputStream trimXML = new ByteArrayOutputStream();
        TrimEx trim = null;
		try {
			trim = getTrimBean().parseTrim( new String(trimHeader.getTrim()), null);
			getCreatorBean().computeScan( trim, TolvenRequest.getInstance().getAccountUser(), null, new Date(), null);
			TrimMarshaller trimMarshaller = new TrimMarshaller();
			
			trimMarshaller.marshalTRIM(trim, trimXML);
		} catch (JAXBException e) {
			 return Response.status(Status.NOT_FOUND).type(MediaType.TEXT_PLAIN).entity("error computing trim :"+name).build();
		}
       return Response.ok().type(MediaType.APPLICATION_XML_TYPE).entity(new String(trimXML.toByteArray())).build();
    }
    
    /**
     * Get a trim by name
     * @param name
     * @return
     * @throws JAXBException 
     */
    @Path("getValuesets")
    @GET
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_JSON)
    public Response getTrimValuesets(@QueryParam("name") String trimNames) throws JAXBException {
    	if(logger.isDebugEnabled())
    		logger.debug("Start: getTrimValuesets for "+trimNames);
    	if(trimNames == null || trimNames.trim().length() == 0){
    		return Response.status(Status.BAD_REQUEST).type(MediaType.TEXT_PLAIN).entity("Invalid argument for trimNames").build();
    	}
    	String names[] = trimNames.split(",");
    	JsonArray sets = new JsonArray();
        for(int i=0;i<names.length;i++){
        	TrimHeader trimHeader = getTrimBean().findOptionalTrimHeader(names[i]);
            TrimEx trim = getTrimBean().parseTrim( new String(trimHeader.getTrim()), null);
            getCreatorBean().computeScan( trim, TolvenRequest.getInstance().getAccountUser(), null, new Date(), null);
            List<ValueSet> valuesets = trim.getValueSets();
            for(ValueSet valueset:valuesets){
            	JsonObject jsonObject = new JsonObject();
            	jsonObject.addProperty("name", valueset.getName());
            	JsonArray set = new JsonArray();
            	List<Object> values = valueset.getBindsAndADSAndCDS();
            	for(Object value:values){
            		if(value instanceof CE){
            			CE ce = (CE) value;
            			JsonObject valueJson = new JsonObject();
            			valueJson.addProperty("displayName", ce.getDisplayName());
            			valueJson.addProperty("code", ce.getCode());
            			valueJson.addProperty("codeSystem", ce.getCodeSystem());
            			valueJson.addProperty("codeSystemVersion", ce.getCodeSystemVersion());
            			set.add(valueJson);		
            		}
            	}
            	jsonObject.add("values", set);
            	sets.add(jsonObject);
            }	
    	}        
        if(logger.isDebugEnabled())
    		logger.debug("End: getTrimValuesets for "+trimNames);
        return Response.ok().type(MediaType.APPLICATION_JSON).entity(sets.toString()).build();
    }
    
   
    protected TrimLocal getTrimBean() {
        if (trimBean == null) {
            String jndiName = "java:app/tolvenEJB/TrimBean!org.tolven.app.TrimLocal";
            try {
                InitialContext ctx = new InitialContext();
                trimBean = (TrimLocal) ctx.lookup(jndiName);
            } catch (Exception ex) {
                throw new RuntimeException("Could not lookup " + jndiName);
            }
        }
        return trimBean;
    }

}
